### PR TITLE
Update Prettier to version 1.12.1

### PR DESCRIPTION
**Pull request by aslatter**
This updates JavaScriptPrettier to the current release of prettier.

This is un-tested - I was going to let your setup of AppVeyor do the build for me (it looks like it will build pull-requests?). I'll update this PR once I've tried out the vsix.

### CODE REVIEW

**Comment by aslatter** [comment]
The built vsix works for me.

**Comment by DarkCow** [comment]
the built vsix works for me too. Thanks

**Comment by jesperbjensen** [comment]
Hi @aslatter 

I'm helping Mads maintain the repo, so we can get som releases and bug fixes out. Do you see any problems if we instead upgrade to the latest version? (1.12.1)

If not - then can you update your pull request to point to that version? (Or else I'm afraid that you will loose your contributor badge)

If you see a problem using that version - we will just merge your pull request for now. I'm thinking that we need to look into some way that you can control the version of prettier - or as a #16 points out - a way to control it using your package.json file. But we need to get a better version of prettier out soon - as the one bundled in the release version is way to old.

**Comment by aslatter** [comment]
I'm okay with 1.12.1. I won't be able to update the PR until this evening - if you move quicker than that it's fine with me.

**Comment by jesperbjensen** [comment]
@aslatter Thank you 😄 

To get the extension build from the master branch - you can get it here: http://vsixgallery.com/extension/J1da7ad9e-85b3-4a0c-8e45-b2ae59a575a7/

I will ask Mads to make a new public release - when I have tried the new version a bit.

**Pull request merged**
